defmodule Kudzu.Brain.LearningGoal do
  @moduledoc """
  A structured learning goal. Created when a user says "Learn X".
  Contains a curriculum of topics generated by Claude, worked through
  autonomously by the Brain's web learning loop.
  """

  defstruct [
    :id,
    :topic,
    :created_at,
    status: :active,
    topics: [],
    current_index: 0,
    completed_count: 0,
    failed_count: 0
  ]

  def new(topic, curriculum_items) when is_list(curriculum_items) do
    %__MODULE__{
      id: generate_id(),
      topic: topic,
      created_at: DateTime.utc_now(),
      topics: Enum.map(curriculum_items, &{&1, :pending})
    }
  end

  def next_topic(%__MODULE__{topics: topics, current_index: idx}) do
    case Enum.at(topics, idx) do
      {topic, :pending} -> {topic, idx}
      _ -> nil
    end
  end

  def complete_current(%__MODULE__{} = goal) do
    topics = List.update_at(goal.topics, goal.current_index, fn {t, _} -> {t, :complete} end)
    goal = %{goal |
      topics: topics,
      current_index: goal.current_index + 1,
      completed_count: goal.completed_count + 1
    }
    maybe_finish(goal)
  end

  def fail_current(%__MODULE__{} = goal) do
    topics = List.update_at(goal.topics, goal.current_index, fn {t, _} -> {t, :failed} end)
    goal = %{goal |
      topics: topics,
      current_index: goal.current_index + 1,
      failed_count: goal.failed_count + 1
    }
    maybe_finish(goal)
  end

  def progress_report(%__MODULE__{} = goal) do
    total = length(goal.topics)
    done = goal.completed_count
    failed = goal.failed_count
    pct = if total > 0, do: round(done / total * 100), else: 0

    completed =
      goal.topics
      |> Enum.filter(fn {_, s} -> s == :complete end)
      |> Enum.map(fn {t, _} -> "  [x] #{t}" end)
      |> Enum.join("\n")

    upcoming =
      goal.topics
      |> Enum.drop(goal.current_index)
      |> Enum.take(5)
      |> Enum.map(fn {t, _} -> "  [ ] #{t}" end)
      |> Enum.join("\n")

    header = "Learning: #{goal.topic} (#{done}/#{total} topics, #{pct}%)"
    failed_line = if failed > 0, do: "\nFailed: #{failed}", else: ""

    """
    #{header}#{failed_line}

    Completed:
    #{completed}

    Next up:
    #{upcoming}
    """
    |> String.trim()
  end

  defp maybe_finish(%{current_index: idx, topics: topics} = goal) do
    if idx >= length(topics) do
      %{goal | status: :complete}
    else
      goal
    end
  end

  defp generate_id do
    :crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower)
  end
end
